### PR TITLE
make 0.8.6 compatible

### PR DESCRIPTION
**Pull request by danielrab**
made the changes necessary to work with 0.8.6, also changed the way layers are addressed from by number to by name.

### CODE REVIEW

**Comment by colinbate** [comment]
There are constants on L71 which need to be updated to use `CONST` as well.

**Comment by danielrab** [comment]
I am not sure why it worked in my testing without this, but I changed it now

**Comment by colinbate** [comment]
I believe that is the code path for uploading via URL dragged from a browser.

**Comment by cswendrowski** [comment]
Thanks for the contribution @danielrab - I fixed up a few remaining things, and Drag Upload is now 0.8.x compatible!

**Pull request merged**
